name: publish

on:
  push:
    branches:
      - docker-limit

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          docker pull openpolicyagent/gatekeeper:v3.14.0
          docker image tag openpolicyagent/gatekeeper:v3.14.0  ghcr.io/obmondo/gatekeeper:v3.14.0
          docker push ghcr.io/obmondo/gatekeeper:v3.14.0
